### ISSUE TITLE
Template review recommendation

### ISSUE THREAD

**Issue by praveena-pappu** [AnastasiiaTymoshenko/GTM-Template-Property-Values-from-Array-of-Objects#1]
Hello,

We have approved the template. However, we have recommendation regarding the description for the template.

Please update the description in a more understanding way for user. The current description is not descriptive enough for the user to understand the functionality of the template.

**Comment by AnastasiiaTymoshenko** [comment]
Hello!
I have updated the description in Readme.md file.
